## QTM350 Final Project Data Cleaning

## Research Question: <br> Do higher education levels and GDP per capita contribute to lower adolescent fertility rates across countries?

#### First we create a python conda environment to use for the rest of this project for reproducibility

In [2]:
!conda create -y -n wb-analysis-env -c conda-forge python=3.10 ipykernel=6.29.3 numpy=1.26.4 pandas=2.2.1 matplotlib=3.8.4 seaborn=0.13.2 wbgapi=1.0.12 requests=2.31.0 sqlalchemy=2.0.29
!python -m ipykernel install --user --name wb-analysis-env --display-name "Python (wb-analysis-env)"
!conda activate wb-analysis-env

Retrieving notices: done
Channels:
 - conda-forge
 - defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /opt/anaconda3/envs/wb-analysis-env

  added / updated specs:
    - ipykernel=6.29.3
    - matplotlib=3.8.4
    - numpy=1.26.4
    - pandas=2.2.1
    - python=3.10
    - requests=2.31.0
    - seaborn=0.13.2
    - sqlalchemy=2.0.29
    - wbgapi=1.0.12


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    libpng-1.6.58              |       h132b30e_0         283 KB  conda-forge
    packaging-26.1             |     pyhc364b38_0          87 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         370 KB

The following NEW packages will be INSTALLED:

  _openmp_mutex      conda-forge/osx-arm64::_openmp_mutex-4.5-7_kmp_llvm
  appnope            conda-forge/noarch::appnope-0.1.4-pyhd8ed1ab_1
  asttokens          conda-forge/noarch::asttokens-3.0.1-pyhd8ed1ab_0
  backports.zstd     conda-forge/osx-arm64::backports.zstd-1.3.0-py310h2d60bed_0
  brotli             conda-forge/osx-arm64::brotli-1.2.0-h7d5ae5b_1
  brotli-bin         conda-forge/osx-arm64::brotli-bin-1.2.0-hc919400_1
  brotli-python      conda-forge/osx-arm64::brotli-python-1.2.0-py310h6123dab_1
  bzip2              conda-forge/osx-arm64::bzip2-1.0.8-hd037594_9
  ca-certificates    conda-forge/noarch::ca-certificates-2026.2.25-hbd8a1cb_0
  certifi            conda-forge/noarch::certifi-2026.2.25-pyhd8ed1ab_0
  charset-normalizer conda-forge/noarch::charset-normalizer-3.4.7-pyhd8ed1ab_0
  comm               conda-forge/noarch::comm-0.2.3-pyhe01879c_0
  contourpy          conda-forge/osx-arm64::contourpy-1.3.2-py310h7f4e7e6_0
  cycler             conda-forge/noarch::cycler-0.12.1-pyhcf101f3_2
  debugpy            conda-forge/osx-arm64::debugpy-1.8.20-py310h19b6747_0
  decorator          conda-forge/noarch::decorator-5.2.1-pyhd8ed1ab_0
  exceptiongroup     conda-forge/noarch::exceptiongroup-1.3.1-pyhd8ed1ab_0
  executing          conda-forge/noarch::executing-2.2.1-pyhd8ed1ab_0
  fonttools          conda-forge/osx-arm64::fonttools-4.62.0-py310hb46c203_0
  freetype           conda-forge/osx-arm64::freetype-2.14.3-hce30654_0
  greenlet           conda-forge/osx-arm64::greenlet-3.4.0-py310h19b6747_0
  h2                 conda-forge/noarch::h2-4.3.0-pyhcf101f3_0
  hpack              conda-forge/noarch::hpack-4.1.0-pyhd8ed1ab_0
  hyperframe         conda-forge/noarch::hyperframe-6.1.0-pyhd8ed1ab_0
  idna               conda-forge/noarch::idna-3.11-pyhd8ed1ab_0
  ipykernel          conda-forge/noarch::ipykernel-6.29.3-pyh3cd1d5f_0
  ipython            conda-forge/noarch::ipython-8.37.0-pyh8f84b5b_0
  jedi               conda-forge/noarch::jedi-0.19.2-pyhd8ed1ab_1
  jupyter_client     conda-forge/noarch::jupyter_client-8.8.0-pyhcf101f3_0
  jupyter_core       conda-forge/noarch::jupyter_core-5.9.1-pyhc90fa1f_0
  kiwisolver         conda-forge/osx-arm64::kiwisolver-1.5.0-py310h34990b0_0
  krb5               conda-forge/osx-arm64::krb5-1.22.2-h385eeb1_0
  lcms2              conda-forge/osx-arm64::lcms2-2.18-hdfa7624_0
  lerc               conda-forge/osx-arm64::lerc-4.1.0-h1eee2c3_0
  libblas            conda-forge/osx-arm64::libblas-3.11.0-6_h51639a9_openblas
  libbrotlicommon    conda-forge/osx-arm64::libbrotlicommon-1.2.0-hc919400_1
  libbrotlidec       conda-forge/osx-arm64::libbrotlidec-1.2.0-hc919400_1
  libbrotlienc       conda-forge/osx-arm64::libbrotlienc-1.2.0-hc919400_1
  libcblas           conda-forge/osx-arm64::libcblas-3.11.0-6_hb0561ab_openblas
  libcxx             conda-forge/osx-arm64::libcxx-22.1.3-h55c6f16_0
  libdeflate         conda-forge/osx-arm64::libdeflate-1.25-hc11a715_0
  libedit            conda-forge/osx-arm64::libedit-3.1.20250104-pl5321hafb1f1b_0
  libexpat           conda-forge/osx-arm64::libexpat-2.7.5-hf6b4638_0
  libffi             conda-forge/osx-arm64::libffi-3.5.2-hcf2aa1b_0
  libfreetype        conda-forge/osx-arm64::libfreetype-2.14.3-hce30654_0
  libfreetype6       conda-forge/osx-arm64::libfreetype6-2.14.3-hdfa99f5_0
  libgcc             conda-forge/osx-arm64::libgcc-15.2.0-hcbb3090_18
  libgfortran        conda-forge/osx-arm64::libgfortran-15.2.0-h07b0088_18
  libgfortran5       conda-forge/osx-arm64::libgfortran5-15.2.0-hdae7583_18
  libjpeg-turbo      conda-forge/osx-arm64::libjpeg-turbo-3.1.4.1-h84a0fba_0
  liblapack          conda-forge/osx-arm64::liblapack-3.11.0-6_hd9741b5_openblas
  liblzma            conda-forge/osx-arm64::liblzma-5.8.3-h8088a28_0
  libopenblas        conda-forge/osx-arm64::libopenblas-0.3.32-openmp_he657e61_0
  libpng             conda-forge/osx-arm64::libpng-1.6.58-h132b30e_0
  libsodium          conda-forge/osx-arm64::libsodium-1.0.21-h1a92334_3
  libsqlite          conda-forge/osx-arm64::libsqlite-3.53.0-h1b79a29_0
  libtiff            conda-forge/osx-arm64::libtiff-4.7.1-h4030677_1
  libwebp-base       conda-forge/osx-arm64::libwebp-base-1.6.0-h07db88b_0
  libxcb             conda-forge/osx-arm64::libxcb-1.17.0-hdb1d25a_0
  libzlib            conda-forge/osx-arm64::libzlib-1.3.2-h8088a28_2
  llvm-openmp        conda-forge/osx-arm64::llvm-openmp-22.1.3-hc7d1edf_0
  matplotlib         conda-forge/osx-arm64::matplotlib-3.8.4-py310hb6292c7_2
  matplotlib-base    conda-forge/osx-arm64::matplotlib-base-3.8.4-py310hedb7998_2
  matplotlib-inline  conda-forge/noarch::matplotlib-inline-0.2.1-pyhd8ed1ab_0
  munkres            conda-forge/noarch::munkres-1.1.4-pyhd8ed1ab_1
  ncurses            conda-forge/osx-arm64::ncurses-6.5-h5e97a16_3
  nest-asyncio       conda-forge/noarch::nest-asyncio-1.6.0-pyhd8ed1ab_1
  numpy              conda-forge/osx-arm64::numpy-1.26.4-py310hd45542a_0
  openjpeg           conda-forge/osx-arm64::openjpeg-2.5.4-hd9e9057_0
  openssl            conda-forge/osx-arm64::openssl-3.6.2-hd24854e_0
  packaging          conda-forge/noarch::packaging-26.1-pyhc364b38_0
  pandas             conda-forge/osx-arm64::pandas-2.2.1-py310h401b61c_0
  parso              conda-forge/noarch::parso-0.8.6-pyhcf101f3_0
  patsy              conda-forge/noarch::patsy-1.0.2-pyhcf101f3_0
  pexpect            conda-forge/noarch::pexpect-4.9.0-pyhd8ed1ab_1
  pickleshare        conda-forge/noarch::pickleshare-0.7.5-pyhd8ed1ab_1004
  pillow             conda-forge/osx-arm64::pillow-12.2.0-py310hc037f36_0
  pip                conda-forge/noarch::pip-26.0.1-pyh8b19718_0
  platformdirs       conda-forge/noarch::platformdirs-4.9.6-pyhcf101f3_0
  prompt-toolkit     conda-forge/noarch::prompt-toolkit-3.0.52-pyha770c72_0
  psutil             conda-forge/osx-arm64::psutil-7.2.2-py310haea493c_0
  pthread-stubs      conda-forge/osx-arm64::pthread-stubs-0.4-hd74edd7_1002
  ptyprocess         conda-forge/noarch::ptyprocess-0.7.0-pyhd8ed1ab_1
  pure_eval          conda-forge/noarch::pure_eval-0.2.3-pyhd8ed1ab_1
  pygments           conda-forge/noarch::pygments-2.20.0-pyhd8ed1ab_0
  pyparsing          conda-forge/noarch::pyparsing-3.3.2-pyhcf101f3_0
  pysocks            conda-forge/noarch::pysocks-1.7.1-pyha55dd90_7
  python             conda-forge/osx-arm64::python-3.10.20-h1b19095_0_cpython
  python-dateutil    conda-forge/noarch::python-dateutil-2.9.0.post0-pyhe01879c_2
  python-tzdata      conda-forge/noarch::python-tzdata-2026.1-pyhd8ed1ab_0
  python_abi         conda-forge/noarch::python_abi-3.10-8_cp310
  pytz               conda-forge/noarch::pytz-2026.1.post1-pyhcf101f3_0
  pyyaml             conda-forge/osx-arm64::pyyaml-6.0.3-py310hb46c203_1
  pyzmq              conda-forge/osx-arm64::pyzmq-27.1.0-py310hf0664f0_2
  readline           conda-forge/osx-arm64::readline-8.3-h46df422_0
  requests           conda-forge/noarch::requests-2.31.0-pyhd8ed1ab_0
  scipy              conda-forge/osx-arm64::scipy-1.15.2-py310h32ab4ed_0
  seaborn            conda-forge/noarch::seaborn-0.13.2-hd8ed1ab_3
  seaborn-base       conda-forge/noarch::seaborn-base-0.13.2-pyhd8ed1ab_3
  setuptools         conda-forge/noarch::setuptools-82.0.1-pyh332efcf_0
  six                conda-forge/noarch::six-1.17.0-pyhe01879c_1
  sqlalchemy         conda-forge/osx-arm64::sqlalchemy-2.0.29-py310hd125d64_0
  stack_data         conda-forge/noarch::stack_data-0.6.3-pyhd8ed1ab_1
  statsmodels        conda-forge/osx-arm64::statsmodels-0.14.6-py310hfdc7867_0
  tabulate           conda-forge/noarch::tabulate-0.10.0-pyhcf101f3_0
  tk                 conda-forge/osx-arm64::tk-8.6.13-h010d191_3
  tornado            conda-forge/osx-arm64::tornado-6.5.5-py310h72544b6_0
  traitlets          conda-forge/noarch::traitlets-5.14.3-pyhd8ed1ab_1
  typing-extensions  conda-forge/noarch::typing-extensions-4.15.0-h396c80c_0
  typing_extensions  conda-forge/noarch::typing_extensions-4.15.0-pyhcf101f3_0
  tzdata             conda-forge/noarch::tzdata-2025c-hc9c84f9_1
  unicodedata2       conda-forge/osx-arm64::unicodedata2-17.0.1-py310h72544b6_0
  urllib3            conda-forge/noarch::urllib3-2.6.3-pyhd8ed1ab_0
  wbgapi             conda-forge/noarch::wbgapi-1.0.12-pyhd8ed1ab_0
  wcwidth            conda-forge/noarch::wcwidth-0.6.0-pyhd8ed1ab_0
  wheel              conda-forge/noarch::wheel-0.46.3-pyhd8ed1ab_0
  xorg-libxau        conda-forge/osx-arm64::xorg-libxau-1.0.12-hc919400_1
  xorg-libxdmcp      conda-forge/osx-arm64::xorg-libxdmcp-1.1.5-hc919400_1
  yaml               conda-forge/osx-arm64::yaml-0.2.5-h925e9cb_3
  zeromq             conda-forge/osx-arm64::zeromq-4.3.5-h4818236_10
  zlib-ng            conda-forge/osx-arm64::zlib-ng-2.3.3-hed4e4f5_1
  zstd               conda-forge/osx-arm64::zstd-1.5.7-hbf9d68e_6



Downloading and Extracting Packages:
libpng-1.6.58        | 283 KB    |                                       |   0%
packaging-26.1       | 87 KB     |                                       |   0%
packaging-26.1       | 87 KB     | ##################################### | 100%


Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate wb-analysis-env
#
# To deactivate an active environment, use
#
#     $ conda deactivate

0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
Installed kernelspec wb-analysis-env in /Users/sissili/Library/Jupyter/kernels/wb-analysis-env

CondaError: Run 'conda init' before 'conda activate'

#### We import the wbgapi package to fetch data directly from the World Bank and standard libraries for file handling.

#### Data fetch - for 5-year-duration

In [2]:
import wbgapi as wb
import pandas as pd
import sqlite3

# 1. Define the indicators
indicators = {
    'SP.ADO.TFRT': 'adolescent_fertility',
    'SE.PRM.ENRR': 'primary_education',
    'SE.SEC.ENRR': 'secondary_education',
    'SE.TER.ENRR': 'tertiary_education',
    'NY.GDP.PCAP.CD': 'gdp_per_capita'
}

# 2. Fetch data specifically for 2020-2024
# Using columns='series' ensures the indicators become the columns
# labels=True gives us the readable country names
df = wb.data.DataFrame(indicators.keys(), time=range(2020, 2025), labels=True, columns='series').reset_index()

# 3. Clean up the column names
# The columns will likely be named 'economy', 'time', and the indicator codes
df = df.rename(columns={
    'economy': 'country_code',
    'CountryName': 'Country',
    'time': 'year',
    'NY.GDP.PCAP.CD': 'gdp_per_capita',
    'SE.PRM.ENRR': 'primary_education',
    'SE.SEC.ENRR': 'secondary_education',
    'SE.TER.ENRR': 'tertiary_education',
    'SP.ADO.TFRT': 'adolescent_fertility'
})

# 4. Save to SQL
conn = sqlite3.connect(':memory:')
df.to_sql('wdi_raw', conn, index=False, if_exists='replace')

# 5. Look at the result 
df.head(10)

,country_code,year,Country,Time,gdp_per_capita,primary_education,secondary_education,tertiary_education,adolescent_fertility
0,ZWE,YR2024,Zimbabwe,2024,2497.203322,93.077211,NaN,7.74913,95.524
1,ZWE,YR2023,Zimbabwe,2023,2195.224921,93.238379,NaN,NaN,98.057
2,ZWE,YR2022,Zimbabwe,2022,2536.400502,93.165966,NaN,NaN,99.484
3,ZWE,YR2021,Zimbabwe,2021,2613.605421,92.784691,NaN,NaN,99.199
4,ZWE,YR2020,Zimbabwe,2020,2059.674454,93.612586,NaN,NaN,98.893
5,ZMB,YR2024,Zambia,2024,1187.109434,115.550919,56.788929,NaN,115.479
6,ZMB,YR2023,Zambia,2023,1330.727806,NaN,NaN,NaN,115.907
7,ZMB,YR2022,Zambia,2022,1447.123101,NaN,NaN,NaN,117.398
8,ZMB,YR2021,Zambia,2021,1127.160779,NaN,NaN,NaN,118.744
9,ZMB,YR2020,Zambia,2020,951.644317,NaN,NaN,NaN,120.712

In [3]:
query = """
SELECT 
    Country,
    AVG(gdp_per_capita) AS avg_gdp,
    AVG(primary_education) AS avg_pri_edu,
    AVG(secondary_education) AS avg_sec_edu,
    AVG(tertiary_education) AS avg_tert_edu,
    AVG(adolescent_fertility) AS avg_fertility
FROM wdi_raw
WHERE Country NOT LIKE '%income%' 
GROUP BY Country
HAVING avg_gdp IS NOT NULL;
"""
pd.read_sql(query, conn).head(10)

,Country,avg_gdp,avg_pri_edu,avg_sec_edu,avg_tert_edu,avg_fertility
0,Afghanistan,409.575581,112.230904,59.613602,10.854360,65.276800
1,Africa Eastern and Southern,1556.036202,102.126631,45.175237,8.686865,93.455051
2,Africa Western and Central,1907.064196,89.538686,45.736360,10.062820,95.914560
3,Albania,8427.195098,99.745033,99.081844,66.616413,13.004200
4,Algeria,4797.574513,106.245699,103.659765,54.189083,9.100200
5,American Samoa,15914.292694,NaN,NaN,NaN,34.279400
6,Andorra,43663.387382,93.386685,99.026561,39.080248,3.405200
7,Angola,2665.477712,87.981001,52.309529,10.002132,141.983600
8,Antigua and Barbuda,19572.081585,116.909307,108.340344,NaN,33.229200
9,Arab World,7096.978884,89.974500,68.457329,33.298216,45.522724

In [4]:
conn.execute("CREATE VIEW IF NOT EXISTS cleaned_country_data AS " + query)

#### Data Cleaning

In [8]:
# Create a "Long" version for time-series analysis
long_query = """
SELECT 
    Country,
    Year,
    gdp_per_capita AS gdp,
    primary_education AS primary_edu,
    secondary_education AS secondary_edu,
    adolescent_fertility AS fertility
FROM wdi_raw
WHERE Country IN ('Brazil', 'Switzerland', 'Italy', 'Malaysia', 'Niger', 'India')
ORDER BY Country, Year;
"""

df_long = pd.read_sql(long_query, conn)

print("df_long created! Dimensions:", df_long.shape)
display(df_long.head(10))

df_long created! Dimensions: (30, 6)

  Country    year           gdp  primary_edu  secondary_edu  fertility
0  Brazil  YR2020   7074.194075   105.912231     103.882660     47.460
1  Brazil  YR2021   7972.536961   103.929398     106.298462     45.670
2  Brazil  YR2022   9281.332821   104.667419     105.702370     42.881
3  Brazil  YR2023  10377.589772          NaN            NaN     42.686
4  Brazil  YR2024  10310.548878   104.296913     104.144661     41.459
5   India  YR2020   1907.042516   101.291254      77.627155     14.423
6   India  YR2021   2239.613844   102.316124      80.624640     14.289
7   India  YR2022   2347.448294   111.084456      81.177861     14.185
8   India  YR2023   2530.120313   112.031232      78.863959     14.060
9   India  YR2024   2694.737809   120.520369      78.105807     13.036

#### Data Cleaning - creating the view

In [13]:
# Create the cleaned view inside SQL
conn.execute("DROP VIEW IF EXISTS cleaned_research_data")
conn.execute("""
CREATE VIEW cleaned_research_data AS
SELECT 
    Country,
    AVG(gdp_per_capita) AS gdp,
    AVG(primary_education) AS primary_edu,
    AVG(secondary_education) AS secondary_edu,
    AVG(tertiary_education) AS tertiary_edu,
    AVG(adolescent_fertility) AS fertility
FROM wdi_raw
WHERE Country IN ('Brazil', 'Switzerland', 'Italy', 'Malaysia', 'Niger', 'India')
GROUP BY Country
HAVING gdp IS NOT NULL 
   AND fertility IS NOT NULL;
""")
print("Cleaned view created successfully.")

Cleaned view created successfully.

#### Save the data

In [14]:
import os

# 1. Define your directory (ensure it exists)
DATA_DIR = '/Users/sissili/Desktop/QTM350/QTM_350_Final_Project/QTM350_Final_Project_Data' 
if not os.path.exists(DATA_DIR):
    os.makedirs(DATA_DIR)

# 2. Pull the final cleaned data from your SQL View into a DataFrame
df_clean = pd.read_sql("SELECT * FROM cleaned_research_data", conn)

# 3. Define the output path and save
output_path = os.path.join(DATA_DIR, 'cleaned_final_project_data.csv')
df_clean.to_csv(output_path, index=False)

print(f"Data successfully exported to: {output_path}")

output_path_long = os.path.join(DATA_DIR, 'cleaned_final_project_data_long.csv')
df_long.to_csv(output_path_long, index=False)
print(f"Long data exported to: {output_path_long}")

Data successfully exported to: /Users/sissili/Desktop/QTM350/QTM_350_Final_Project/QTM350_Final_Project_Data/cleaned_final_project_data.csv
Long data exported to: /Users/sissili/Desktop/QTM350/QTM_350_Final_Project/QTM350_Final_Project_Data/cleaned_final_project_data_long.csv